---
- hosts: localhost
  tasks:
    - name: Deploy a Docker container
      docker_container:
        image: nginx:stable
        name: bahman_nginx
        state: started
        ports:
          - "8088:80"
