---
- hosts: localhost
  tasks:
   - name: making sure the /tmp has more than 1 gb
     shell: "df -h /tmp | grep -v File | awk '{print $4}' | cut -d G -f1"
     register: tmpspace
     failed_when: "tmpspace.stdout|float < 1"


   - name: making sure /opt has more than 4 gb
     shell: "df -h /opt | grep -v File | awk '{print $4}' | cut -d G -f1"
     register: optspace
     failed_when: "tmpspace.stdout|float < 4"

   - name: make sure RAM is more 16gb
     shell: "cat /proc/meminfo | grep -i memtotal | awk '{print $2/1024/1024}'"
     register: memory
     failed_when: "memory.stdout|float < 16"
